version: '2'

services:
  frontend:
    build: .
    volumes:
      - ./src:/opt/restaurant/src
      - data:/var/uploads
    ports:
      - 8000:8000
    links:
      - postgres
    environment:
      DB_HOST: postgres

  postgres:
    image: postgres:9.6.1
    volumes:
      - data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: restaurant

volumes:
  data:
